name: Battle bro
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup SDKs
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          flutter-version: 3.3.1
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email jubal2000@gmail.com
          git config --global user.name jubal2000
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/jubal2000/Battle-bro-00.git 
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
